services:
  # Contenedor de la base de datos (POSTGRESQL)
  postgres:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5000:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: playle

  # Contenedor del backend
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=playle

  # Contenedor del frontend
  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    

      